plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.example.psxvcdconverter"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.example.psxvcdconverter"
        minSdk = 24
        targetSdk = 34

        // --- AUTOMATIC VERSIONING (GitHub Actions) ---
        // Reads 'BUILD_NUMBER' from the workflow. Defaults to 1 if running locally.
        val buildNumber = System.getenv("BUILD_NUMBER")?.toIntOrNull() ?: 1
        
        versionCode = buildNumber
        versionName = "2.0.$buildNumber"
        // ---------------------------------------------

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    // --- SIGNING CONFIGURATION (For GitHub Actions) ---
    signingConfigs {
        create("release") {
            // This loads the keystore file generated by the workflow
            val keystoreFile = file("release.jks")
            if (keystoreFile.exists()) {
                storeFile = keystoreFile
                storePassword = System.getenv("KEYSTORE_PASSWORD")
                keyAlias = System.getenv("KEY_ALIAS")
                keyPassword = System.getenv("KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            // 1. SCRAMBLE CODE (Security)
            isMinifyEnabled = true
            
            // 2. REMOVE UNUSED RESOURCES (Size)
            isShrinkResources = true
            
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
            
            // Apply the signing config if the keystore exists
            signingConfig = signingConfigs.getByName("release")
        }
    }
    
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = "11"
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    
    // File Access
    implementation("androidx.documentfile:documentfile:1.0.1")
    
    // Coroutines (Background Tasks)
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
    
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
}